version: "3.5"
services:
  appdev:
    build: .
    image: raspi-route
    container_name: appdev
    volumes:
      - ./release:/home/release
      - ./app:/go/src/app
    working_dir: /go/src/app
    tty: true
